# Generated by Django 4.1.7 on 2023-03-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='page_blocks/')),
                ('content', models.TextField()),
                ('seo_title', models.CharField(max_length=255)),
                ('seo_description', models.CharField(max_length=255)),
                ('seo_keywords', models.CharField(max_length=255)),
                ('template', models.CharField(max_length=255)),
            ],
        ),
    ]
