# Generated by Django 4.1.7 on 2023-03-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageblock',
            name='image',
            field=models.ImageField(null=True, upload_to='page_blocks/'),
        ),
        migrations.AlterField(
            model_name='pageblock',
            name='seo_description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pageblock',
            name='seo_keywords',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pageblock',
            name='seo_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
