# Generated by Django 4.1.7 on 2023-03-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_pageblock_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageblock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='page_blocks/'),
        ),
        migrations.AlterField(
            model_name='pageblock',
            name='seo_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pageblock',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pageblock',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
