# Generated by Django 4.1.7 on 2023-03-23 07:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_pageblock_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='Телефон')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Имя')),
                ('email', models.CharField(blank=True, max_length=80, null=True, unique=True, verbose_name='email')),
                ('text', models.CharField(blank=True, max_length=500, null=True, verbose_name='Сообщение')),
                ('datetime_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время создания')),
                ('complete', models.BooleanField(default=False, verbose_name='Отметка о выполнении')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#0d6efd', max_length=7)),
                ('secondary_color', models.CharField(default='#6c757d', max_length=7)),
                ('success_color', models.CharField(default='#198754', max_length=7)),
                ('info_color', models.CharField(default='#0dcaf0', max_length=7)),
                ('warning_color', models.CharField(default='#ffc107', max_length=7)),
                ('danger_color', models.CharField(default='#dc3545', max_length=7)),
                ('light_color', models.CharField(default='#f8f9fa', max_length=7)),
                ('dark_color', models.CharField(default='#212529', max_length=7)),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.AlterModelOptions(
            name='pageblock',
            options={'verbose_name': 'Блок страницы', 'verbose_name_plural': 'Блоки страницы'},
        ),
    ]
