# Generated by Django 4.1.7 on 2023-03-23 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_redirect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='photos/')),
                ('cropped_image', models.ImageField(upload_to='photos/cropped/')),
                ('order', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('page_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main.pageblock')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фотографии',
                'ordering': ['order'],
            },
        ),
    ]
