# Generated by Django 4.1.7 on 2023-03-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pageblock',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
