# Generated by Django 4.1.7 on 2023-03-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_photo_cropped_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='old_path',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
