# Generated by Django 4.1.7 on 2023-03-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_redirect_old_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirect',
            name='is_root_redirect',
            field=models.BooleanField(default=False),
        ),
    ]
